-- Seed real content (text only; add images via /pntarch panel)
-- Run AFTER schema.sql, in Supabase SQL Editor.

update public.profile set
  name='PHAM NGOC THIEM', role='ARCHITECT', email='pnt.architect.work@gmail.com', phone='0888284998',
  address_vi='Vinhomes Smart City, Tây Mỗ, Nam Từ Liêm, Hà Nội', address_en='Vinhomes Smart City, Tay Mo, South Tu Liem, Ha Noi', location_label='Ha Noi',
  languages=ARRAY['Vietnamese','English']::text[], summary_vi='Kiến trúc sư với hơn 6 năm kinh nghiệm trong các dự án nhà ở, cơ sở giáo dục và quy hoạch đô thị. Thành thạo trong việc phối hợp BIM, triển khai mô hình và nâng cao sự hợp tác trong nhóm. Sử dụng thành thạo Revit, Navisworks, PowerBI, AutoCAD và tài liệu kỹ thuật.', summary_en='Architect with over 6 years of experience in residential, educational, and urban planning projects. Skilled in BIM coordination, model implementation, and enhancing team collaboration. Proficient in Revit, Navisworks, PowerBI, AutoCAD, and technical documentation.',
  home_headline_vi='PHAM NGOC THIEM', home_headline_en='Architect · BIM Coordinator',
  home_subline_vi='Kiến trúc sư với hơn 6 năm kinh nghiệm trong các dự án nhà ở, cơ sở giáo dục và quy hoạch đô thị.', home_subline_en='Architect with over 6 years of experience in residential, educational, and urban planning projects.'
where id=1;

delete from public.experiences; delete from public.education; delete from public.skills; delete from public.project_images; delete from public.projects;

insert into public.experiences (company,timeframe,role_vi,role_en,achievements_vi,achievements_en,sort_order) values ('VietNam National Construction Consultants (VNCC)','2022 – Present (Ha Noi)','Chuyên gia Revit – Điều phối viên BIM – Quản lý BIM','Revit Specialist – BIM Coordinator – BIM Manager',ARRAY['Đảm nhận vai trò điều phối viên BIM trong nhiều dự án quy mô lớn, chịu trách nhiệm kiểm soát chất lượng mô hình và phối hợp các bộ môn.','Đóng góp xây dựng Kế hoạch Thi hành BIM (BEP) cho Cảng hàng không quốc tế Long Thành.','Tham gia quản lý chiến lược BIM, phát triển nhóm R&D, cải thiện quy trình thiết kế số và tiêu chuẩn BIM. Tổ chức đào tạo Revit nội bộ.']::text[],ARRAY['Served as BIM Coordinator on large-scale projects, responsible for model quality control and interdisciplinary coordination.','Contributed to the BIM Execution Plan (BEP) for Long Thanh International Airport.','Participated in BIM strategy management and developed the office''s R&D team, improving digital design workflows and BIM standards. Conducted internal Revit training.']::text[],2);
insert into public.experiences (company,timeframe,role_vi,role_en,achievements_vi,achievements_en,sort_order) values ('DLLC Urban Development & Architectural Design Consultant','2021 – 2022 (Ha Noi)','KTS Concept','Conceptual Architect',ARRAY['Khởi xướng và phát triển ý tưởng thiết kế cho các cơ sở giáo dục và dự án quy hoạch đô thị.','Tham gia giai đoạn phát triển ý tưởng của một dự án quy hoạch tổng thể cùng Nikken Sekkei.']::text[],ARRAY['Initiated and developed design concepts for educational facilities and urban planning projects.','Participated in the concept development phase of a master planning project with Nikken Sekkei.']::text[],1);
insert into public.experiences (company,timeframe,role_vi,role_en,achievements_vi,achievements_en,sort_order) values ('EBROS C&T VIET NAM Joint Stock Company','2019 – 2021 (Ha Noi)','Thực tập – Triển khai – KTS Concept','Internship – Drafting – Concept',ARRAY['Thiết kế và phát triển ý tưởng cho các dự án quy mô nhỏ, bao gồm không gian thờ cúng tâm linh.','Tạo thiết kế nội thất cho không gian nhà ở và render ở các góc nhìn nội/ngoại thất.']::text[],ARRAY['Designed and developed concepts for small-scale projects, including spiritual worship spaces.','Created interior designs for residential spaces and rendered interior/exterior views.']::text[],0);

insert into public.education (name,description_vi,description_en,sort_order) values ('Ha Noi Architectural University','2016 – 2021 (Hà Nội) – Cử nhân Kiến Trúc','2016 – 2021 (Ha Noi) – The degree of Architect',0);
insert into public.education (name,description_vi,description_en,sort_order) values ('Vecas – Autodesk (BIM Coordinator Course)','2023 (Hà Nội) – Chứng nhận Điều phối BIM','2023 (Ha Noi) – BIM Coordinator Certificate',1);
insert into public.education (name,description_vi,description_en,sort_order) values ('Vecas (GIS in Construction Planning)','2025 (Hà Nội) – Chứng nhận hoàn thành khóa học GIS','2025 (Ha Noi) – Certificate of Completion for GIS Course',2);

insert into public.skills (title,level,percent,sort_order) values ('Autodesk Revit','Expert',100,0);
insert into public.skills (title,level,percent,sort_order) values ('Autodesk Navisworks','Expert',100,1);
insert into public.skills (title,level,percent,sort_order) values ('Adobe Photoshop','Expert',100,2);
insert into public.skills (title,level,percent,sort_order) values ('Microsoft Power BI','Experienced',78,3);
insert into public.skills (title,level,percent,sort_order) values ('Adobe Illustrator','Experienced',78,4);
insert into public.skills (title,level,percent,sort_order) values ('Adobe InDesign','Experienced',78,5);
insert into public.skills (title,level,percent,sort_order) values ('Microsoft Office','Experienced',78,6);
insert into public.skills (title,level,percent,sort_order) values ('Lumion','Skillful',58,7);
insert into public.skills (title,level,percent,sort_order) values ('Autodesk AutoCAD','Beginner',32,8);
insert into public.skills (title,level,percent,sort_order) values ('Sketch Up','Beginner',32,9);

insert into public.projects (slug,title_vi,title_en,construction_class_vi,construction_class_en,location_vi,location_en,primary_role_vi,primary_role_en,overview_vi,overview_en,responsibilities_vi,responsibilities_en,sort_order) values ('xuan-dai-bay','Tổ hợp du lịch nghỉ dưỡng Xuân Đài Bay','Xuan Dai Bay resort and tourism Complex','Cấp công trình: II','Construction Class: II','Phú Yên, Việt Nam','Phu Yen, Viet Nam','Triển khai chính','Main deployment','Thông tin dự án theo CV (Kinh nghiệm – Vai trò chính).','Project information follows the CV (Experience – Primary Role).',ARRAY['Triển khai hồ sơ kiến trúc (bản vẽ chi tiết) và phối hợp các bên liên quan.','Thực hiện phối cảnh / render phục vụ trình bày.']::text[],ARRAY['Prepared architectural deliverables (detailed drawings) and coordinated with stakeholders.','Produced render/perspective views for presentation.']::text[],0);
insert into public.projects (slug,title_vi,title_en,construction_class_vi,construction_class_en,location_vi,location_en,primary_role_vi,primary_role_en,overview_vi,overview_en,responsibilities_vi,responsibilities_en,sort_order) values ('vung-lam-phu-yen','Khu nghỉ dưỡng Vũng Lâm Phú Yên','Vung Lam Phu Yen resort','Cấp công trình: I','Construction Class: I','Phú Yên, Việt Nam','Phu Yen, Viet Nam','Triển khai chính','Main deployment','Vai trò tập trung vào điều phối BIM và triển khai hồ sơ theo CV.','Role focused on BIM coordination and deliverables, as described in the CV.',ARRAY['Điều phối BIM, kiểm soát chất lượng mô hình và phối hợp liên bộ môn.','Tham gia xây dựng / triển khai BEP (BIM Execution Plan) theo yêu cầu dự án.','Chuẩn hóa quy trình BIM và hỗ trợ đào tạo nội bộ.','Triển khai hồ sơ kiến trúc (bản vẽ chi tiết) và phối hợp các bên liên quan.','Thực hiện phối cảnh / render phục vụ trình bày.']::text[],ARRAY['BIM coordination, model quality control, and interdisciplinary coordination.','Contributed to / implemented the BIM Execution Plan (BEP) per project requirements.','Improved BIM standards and supported internal training.','Prepared architectural deliverables (detailed drawings) and coordinated with stakeholders.','Produced render/perspective views for presentation.']::text[],1);
insert into public.projects (slug,title_vi,title_en,construction_class_vi,construction_class_en,location_vi,location_en,primary_role_vi,primary_role_en,overview_vi,overview_en,responsibilities_vi,responsibilities_en,sort_order) values ('bai-lu-resort','Khu nghỉ dưỡng Bãi Lữ','Bai Lu resort','Cấp công trình: I','Construction Class: I','Nghệ An, Việt Nam','Nghe An, Viet Nam','Triển khai chính','Main deployment','Thông tin dự án theo CV (Kinh nghiệm – Vai trò chính).','Project information follows the CV (Experience – Primary Role).',ARRAY['Triển khai hồ sơ kiến trúc (bản vẽ chi tiết) và phối hợp các bên liên quan.','Thực hiện phối cảnh / render phục vụ trình bày.']::text[],ARRAY['Prepared architectural deliverables (detailed drawings) and coordinated with stakeholders.','Produced render/perspective views for presentation.']::text[],2);
insert into public.projects (slug,title_vi,title_en,construction_class_vi,construction_class_en,location_vi,location_en,primary_role_vi,primary_role_en,overview_vi,overview_en,responsibilities_vi,responsibilities_en,sort_order) values ('social-housing-x2','Nhà ở xã hội chung cư X2','Social Housing: X2 Apartment Complex','Cấp công trình: II','Construction Class: II','Hà Nội, Việt Nam','Ha Noi, Viet Nam','Triển khai chính','Main deployment','Vai trò theo CV, nhấn mạnh điều phối BIM và phối hợp liên bộ môn.','Role follows the CV, emphasizing BIM coordination and interdisciplinary coordination.',ARRAY['Điều phối BIM, kiểm soát chất lượng mô hình và phối hợp liên bộ môn.','Tham gia xây dựng / triển khai BEP (BIM Execution Plan) theo yêu cầu dự án.','Chuẩn hóa quy trình BIM và hỗ trợ đào tạo nội bộ.','Triển khai hồ sơ kiến trúc (bản vẽ chi tiết) và phối hợp các bên liên quan.','Thực hiện phối cảnh / render phục vụ trình bày.']::text[],ARRAY['BIM coordination, model quality control, and interdisciplinary coordination.','Contributed to / implemented the BIM Execution Plan (BEP) per project requirements.','Improved BIM standards and supported internal training.','Prepared architectural deliverables (detailed drawings) and coordinated with stakeholders.','Produced render/perspective views for presentation.']::text[],3);
insert into public.projects (slug,title_vi,title_en,construction_class_vi,construction_class_en,location_vi,location_en,primary_role_vi,primary_role_en,overview_vi,overview_en,responsibilities_vi,responsibilities_en,sort_order) values ('viet-han-college-quang-ninh','Trường Cao đẳng Việt – Hàn Quảng Ninh','Viet – Han College Quang Ninh','Cấp công trình: II','Construction Class: II','Quảng Ninh, Việt Nam','Quang Ninh, Viet Nam','Triển khai chính','Main deployment','Thông tin dự án theo CV (Kinh nghiệm – Vai trò chính).','Project information follows the CV (Experience – Primary Role).',ARRAY['Triển khai hồ sơ kiến trúc (bản vẽ chi tiết) và phối hợp các bên liên quan.','Thực hiện phối cảnh / render phục vụ trình bày.']::text[],ARRAY['Prepared architectural deliverables (detailed drawings) and coordinated with stakeholders.','Produced render/perspective views for presentation.']::text[],4);
insert into public.projects (slug,title_vi,title_en,construction_class_vi,construction_class_en,location_vi,location_en,primary_role_vi,primary_role_en,overview_vi,overview_en,responsibilities_vi,responsibilities_en,sort_order) values ('hue-golf-clubhouse','Sân golf Huế','Hue golf clubhouse','Cấp công trình: III','Construction Class: III','Huế, Việt Nam','Hue, Viet Nam','Triển khai chính – Điều phối BIM','Main deployment – BIM Coordinator','Thông tin dự án theo CV (Kinh nghiệm – Vai trò chính).','Project information follows the CV (Experience – Primary Role).',ARRAY['Triển khai hồ sơ kiến trúc (bản vẽ chi tiết) và phối hợp các bên liên quan.','Thực hiện phối cảnh / render phục vụ trình bày.']::text[],ARRAY['Prepared architectural deliverables (detailed drawings) and coordinated with stakeholders.','Produced render/perspective views for presentation.']::text[],5);
insert into public.projects (slug,title_vi,title_en,construction_class_vi,construction_class_en,location_vi,location_en,primary_role_vi,primary_role_en,overview_vi,overview_en,responsibilities_vi,responsibilities_en,sort_order) values ('vtvs1-studio-central-square','Trường quay VTV.S1 và Quảng trường trung tâm','VTV.S1 television studio and Central Square','Cấp công trình: II','Construction Class: II','Hà Nội, Việt Nam','Ha Noi, Viet Nam','Triển khai chính – Điều phối BIM','Main deployment – BIM Coordinator','Thông tin dự án theo CV (Kinh nghiệm – Vai trò chính).','Project information follows the CV (Experience – Primary Role).',ARRAY['Triển khai hồ sơ kiến trúc (bản vẽ chi tiết) và phối hợp các bên liên quan.','Thực hiện phối cảnh / render phục vụ trình bày.']::text[],ARRAY['Prepared architectural deliverables (detailed drawings) and coordinated with stakeholders.','Produced render/perspective views for presentation.']::text[],6);
insert into public.projects (slug,title_vi,title_en,construction_class_vi,construction_class_en,location_vi,location_en,primary_role_vi,primary_role_en,overview_vi,overview_en,responsibilities_vi,responsibilities_en,sort_order) values ('vung-bau-golf-clubhouse','Sân golf Vũng Bầu','Vung Bau golf clubhouse','Cấp công trình: III','Construction Class: III','Phú Quốc, Việt Nam','Phu Quoc, Viet Nam','Triển khai chính','Main deployment','Vai trò điều phối BIM theo CV.','BIM coordination role per the CV.',ARRAY['Điều phối BIM, kiểm soát chất lượng mô hình và phối hợp liên bộ môn.','Tham gia xây dựng / triển khai BEP (BIM Execution Plan) theo yêu cầu dự án.','Chuẩn hóa quy trình BIM và hỗ trợ đào tạo nội bộ.']::text[],ARRAY['BIM coordination, model quality control, and interdisciplinary coordination.','Contributed to / implemented the BIM Execution Plan (BEP) per project requirements.','Improved BIM standards and supported internal training.']::text[],7);
insert into public.projects (slug,title_vi,title_en,construction_class_vi,construction_class_en,location_vi,location_en,primary_role_vi,primary_role_en,overview_vi,overview_en,responsibilities_vi,responsibilities_en,sort_order) values ('viettel-tower-da-nang','Tòa nhà Viettel Đà Nẵng','Viettel Tower Da Nang','Cấp công trình: I','Construction Class: I','Đà Nẵng, Việt Nam','Da Nang, Viet Nam','Điều phối BIM','BIM Coordinator','Thông tin dự án theo CV (Kinh nghiệm – Vai trò chính).','Project information follows the CV (Experience – Primary Role).',ARRAY['Triển khai hồ sơ kiến trúc (bản vẽ chi tiết) và phối hợp các bên liên quan.','Thực hiện phối cảnh / render phục vụ trình bày.']::text[],ARRAY['Prepared architectural deliverables (detailed drawings) and coordinated with stakeholders.','Produced render/perspective views for presentation.']::text[],8);
insert into public.projects (slug,title_vi,title_en,construction_class_vi,construction_class_en,location_vi,location_en,primary_role_vi,primary_role_en,overview_vi,overview_en,responsibilities_vi,responsibilities_en,sort_order) values ('long-thanh-international-airport','Cảng hàng không quốc tế Long Thành','Long Thanh International Airport','Cấp công trình: Đặc biệt','Construction Class: Special','Long Thành, Việt Nam','Long Thanh, Viet Nam','Điều phối BIM | Quản lý BIM','BIM Coordinator | BIM Manager','Dự án được nêu trong CV với vai trò BIM Coordinator/BIM Manager và tham gia xây dựng BEP.','Listed in the CV with BIM Coordinator/BIM Manager roles and BEP contribution.',ARRAY['Điều phối BIM, kiểm soát chất lượng mô hình và phối hợp liên bộ môn.','Tham gia xây dựng / triển khai BEP (BIM Execution Plan) theo yêu cầu dự án.','Chuẩn hóa quy trình BIM và hỗ trợ đào tạo nội bộ.']::text[],ARRAY['BIM coordination, model quality control, and interdisciplinary coordination.','Contributed to / implemented the BIM Execution Plan (BEP) per project requirements.','Improved BIM standards and supported internal training.']::text[],9);
